global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Microsoft.AspNetCore.Http.Connections;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.AspNetCore.SignalR.Client;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using XForge.Sync.Transport;
